FlightPlanner/urls.py
from django.conf.urls import patterns, url

from FlightPlanner import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

PlacesPlanner/urls.py
from django.conf.urls import patterns, url

from PlacesPlanner import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^category-list$', views.category_list, name='category_list')
)

TravelPlanner/urls.py
import os

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from TravelPlanner import settings


urlpatterns = patterns('',
    url(r'^flight/', include('FlightPlanner.urls', namespace='FlightPlanner')),
    url(r'^place/', include('PlacesPlanner.urls', namespace='PlacesPlanner')),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

FlightPlanner/models.py
from django.db import models

# Create your models here.

PlacesPlanner/models.py
from django.db import models

# Create your models here.

PlacesPlanner/forms.py
from django import forms

from TravelPlanner.lib.forms import Form


class PlaceSearchForm(Form):
    destination_city = forms.CharField(label='Destination City', max_length=100)

TravelPlanner/lib/forms.py
from django import forms
from django.utils.safestring import mark_safe
from django.utils.html import conditional_escape, format_html
from django.utils.encoding import smart_text, force_text
from django.utils import six


class Form(forms.Form):
    def _html_output(self, normal_row, error_row, row_ender, help_text_html, errors_on_separate_row):
        "Helper function for outputting HTML. Used by as_table(), as_ul(), as_p()."

        normal_row = '<div class="form-group %(html_class_attr)s">%(label)s%(errors)s%(field)s%(help_text)s</div>'

        top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
        output, hidden_fields = [], []

        for name, field in self.fields.items():
            if 'class' in field.widget.attrs and 'form-control' not in field.widget.attrs['class']:
                field.widget.attrs['class'] += 'form-control'
            else:
                field.widget.attrs['class'] = 'form-control'

            html_class_attr = ''
            bf = self[name]
            # Escape and cache in local variable.
            bf_errors = self.error_class([conditional_escape(error) for error in bf.errors])
            if bf.is_hidden:
                if bf_errors:
                    top_errors.extend(
                        [_('(Hidden field %(name)s) %(error)s') % {'name': name, 'error': force_text(e)}
                         for e in bf_errors])
                hidden_fields.append(six.text_type(bf))
            else:
                # Create a 'class="..."' attribute if the row should have any
                # CSS classes applied.
                css_classes = bf.css_classes()

                if css_classes:
                    html_class_attr = ' class="%s"' % css_classes

                if errors_on_separate_row and bf_errors:
                    output.append(error_row % force_text(bf_errors))

                if bf.label:
                    label = conditional_escape(force_text(bf.label))
                    label = bf.label_tag(label) or ''
                else:
                    label = ''

                if field.help_text:
                    help_text = help_text_html % force_text(field.help_text)
                else:
                    help_text = ''

                output.append(normal_row % {
                    'errors': force_text(bf_errors),
                    'label': force_text(label),
                    'field': six.text_type(bf),
                    'help_text': help_text,
                    'html_class_attr': html_class_attr,
                    'field_name': bf.html_name,
                })

        if top_errors:
            output.insert(0, error_row % force_text(top_errors))

        if hidden_fields:  # Insert any hidden fields in the last row.
            str_hidden = ''.join(hidden_fields)
            if output:
                last_row = output[-1]
                # Chop off the trailing row_ender (e.g. '</td></tr>') and
                # insert the hidden fields.
                if not last_row.endswith(row_ender):
                    # This can happen in the as_p() case (and possibly others
                    # that users write): if there are only top errors, we may
                    # not be able to conscript the last row for our purposes,
                    # so insert a new, empty row.
                    last_row = (normal_row % {'errors': '', 'label': '',
                                              'field': '', 'help_text': '',
                                              'html_class_attr': html_class_attr})
                    output.append(last_row)
                output[-1] = last_row[:-len(row_ender)] + str_hidden + row_ender
            else:
                # If there aren't any rows in the output, just append the
                # hidden fields.
                output.append(str_hidden)
        html_output = mark_safe('\n'.join(output))

        return html_output

FlightPlanner/views.py
import requests
import json

from django.shortcuts import render


def index(request):
    response = requests.get('http://www.flysiesta.lv/xhr2/search/id/RIX/MLE/2015-07-20/2015-07-26/adt-2/chd-0/inf-0/')
    data = json.loads(response.text)

    print(data)

    context = {}

    return render(request, 'FlightPlanner/index.html', context)

PlacesPlanner/views.py
from django.shortcuts import render

from PlacesPlanner.forms import PlaceSearchForm
from TravelPlanner.lib import foursquare


def index(request):
    if request.method == 'POST':
        form = PlaceSearchForm(request.POST)

        destination_city = request.POST['destination_city']

        client = foursquare.get_client()
        explore_venues = client.venues.explore({'near': destination_city, 'section': 'sights'})
        print(explore_venues['geocode']['cc'])
        print(explore_venues['geocode']['displayString'])
        print(explore_venues['headerLocationGranularity'])
    else:
        form = PlaceSearchForm()
        explore_venues = None

    context = {
        'form': form,
        'explore_venues': explore_venues,
    }

    return render(request, 'PlacesPlanner/index.html', context)


def category_list(request):
    client = foursquare.get_client()

    categories = client.venues.categories()

    context = {
        'categories': categories['categories']
    }

    return render(request, 'PlacesPlanner/category_list.html', context)

templates/FlightPlanner/index.html
{% extends 'base_generic.html' %}

{% block content %}
    aaa
{% endblock %}

templates/PlacesPlanner/category_list.html
{% extends 'base_generic.html' %}

{% block content %}
    {% for category in categories %}
        <h1>{{ category.shortName }}</h1>

        {% include 'PlacesPlanner/includes/category.html' with categories=category.categories %}
    {% endfor %}
{% endblock %}

templates/PlacesPlanner/includes/category.html
{% for category in categories %}
    <p>{{ category.shortName }}</p>

    {% if category.categories %}
        {% include 'PlacesPlanner/includes/category.html' with categories=category.categories %}
    {% endif %}
{% endfor %}

templates/PlacesPlanner/index.html
{% extends 'base_generic.html' %}

{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-sm-12 col-md-offset-3">
            <form action="{% url 'PlacesPlanner:index' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit" class="btn btn-primary" />
            </form>
        </div>
    </div>

    {% if explore_venues != None %}
        <div class="row">
            {% for explore_group in explore_venues.groups %}
                {% for explore_item in explore_group.items %}
                    <p>{{ explore_item.venue.name }}</p>
                {% endfor %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/base_ajax.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

templates/base_generic.html
{% extends request.is_ajax|yesno:"base_ajax.html,base_main.html" %}

templates/base_main.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>test</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

    {% block bootstrap_theme %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme-used.css' %}" />
    {% endblock %}

    {% block stylesheets %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    {% endblock %}
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img alt="Brand" src="https://openclipart.org/image/800px/svg_to_png/202320/air-travel.png"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>

    <script src="{% static 'js/jquery-1.11.2.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>